=== bradmAFINIA/InkCostCalculator/InkCostCalculatorL501Enhanced (1)/ConsumableConfigDyn.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dd2="http://www.hp.com/schemas/imaging/con/dictionaries/2008/10/10" xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" xmlns:ccdyn="http://www.hp.com/schemas/imaging/con/ledm/consumableconfigdyn/2007/11/19" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.hp.com/schemas/imaging/con/ledm/consumableconfigdyn/2007/11/19" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import namespace="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" />
  <xs:import namespace="http://www.hp.com/schemas/imaging/con/dictionaries/2008/10/10" />
  <xs:element name="ConsumableConfigDyn">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dd:Version" />
        <xs:element name="ProductConsumableInfo">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="dd:NumOfUserReplaceableConsumables" />
              <xs:element ref="dd:NumOfNonUserReplaceableConsumables" />
              <xs:element ref="dd:AlignmentMode" />
              <xs:element name="CartridgeChipInfo" type="xs:string" />
              <xs:element ref="dd:ConsumableSlotDirection" />
              <xs:element ref="dd:IK" />
              <xs:element name="SingleCartridgeMode" type="xs:string" />
              <xs:element ref="dd:StoreUsageData" />
              <xs:element ref="dd:AntiTheftMode" />
              <xs:element name="RewardsRegistrationStatus">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="dd:OptedIn" />
                    <xs:element ref="dd:AutoSendData" />
                    <xs:element ref="dd:PromptAutoSendData" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="ConsumableInfo">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="dd:Capacity" />
              <xs:element name="ConsumableSubBrand" type="xs:string" />
              <xs:element name="ConsumableSegmentClass" type="xs:string" />
              <xs:element ref="dd:ConsumableAcceptibilityUpgradability" />
              <xs:element ref="dd:ConsumableContentType" />
              <xs:element ref="dd:ConsumableFamilyName" />
              <xs:element ref="dd2:ConsumableID" />
              <xs:element ref="dd:ConsumableKeyingDescriptor" />
              <xs:element ref="dd:ConsumableLabelCode" />
              <xs:element ref="dd:ConsumableLifeState" />
              <xs:element ref="dd:ConsumableStateAvailableActions" />
              <xs:element ref="dd:ConsumableLevelMessagingStyle" />
              <xs:element name="ConsumableLowUseAlgorithm" type="xs:string" />
              <xs:element ref="dd:ConsumablePercentageLevelRemaining" />
              <xs:element ref="dd:ConsumableReplaceabilityType" />
              <xs:element ref="dd:ConsumableSelectibilityNumber" />
              <xs:element ref="dd:ConsumableStation" />
              <xs:element ref="dd:ConsumableTypeEnum" />
              <xs:element ref="dd:RegionalCartridge" />
              <xs:element ref="dd:ConsumableIcon" />
              <xs:element name="ConsumableUniqueID" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema><?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Version">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Revision" type="xs:string" />
        <xs:element name="Date" type="xs:date" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="NumOfUserReplaceableConsumables" type="xs:unsignedByte" />
  <xs:element name="NumOfNonUserReplaceableConsumables" type="xs:unsignedByte" />
  <xs:element name="AlignmentMode" type="xs:string" />
  <xs:element name="ConsumableSlotDirection" type="xs:string" />
  <xs:element name="IK" type="xs:unsignedByte" />
  <xs:element name="StoreUsageData" type="xs:string" />
  <xs:element name="AntiTheftMode" type="xs:string" />
  <xs:element name="OptedIn" type="xs:boolean" />
  <xs:element name="AutoSendData" type="xs:boolean" />
  <xs:element name="PromptAutoSendData" type="xs:boolean" />
  <xs:element name="Capacity">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MaxCapacity" type="xs:unsignedByte" />
        <xs:element name="Unit" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ConsumableAcceptibilityUpgradability" type="xs:string" />
  <xs:element name="ConsumableContentType" type="xs:string" />
  <xs:element name="ConsumableFamilyName" type="xs:string" />
  <xs:element name="ConsumableKeyingDescriptor" type="xs:string" />
  <xs:element name="ConsumableLabelCode" type="xs:string" />
  <xs:element name="ConsumableLifeState">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ConsumableState" type="xs:string" />
        <xs:element name="MeasuredQuantityState" type="xs:string" />
        <xs:element name="Brand" type="xs:string" />
        <xs:element name="IsRefilled" type="xs:boolean" />
        <xs:element name="IsSETUP" type="xs:boolean" />
        <xs:element name="IsTrial" type="xs:boolean" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ConsumableStateAvailableActions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ConsumableState" type="xs:string" />
        <xs:element name="SupportedActions">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="ConsumableStateAction" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="DefaultAction" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ConsumableLevelMessagingStyle" type="xs:string" />
  <xs:element name="ConsumablePercentageLevelRemaining" type="xs:unsignedByte" />
  <xs:element name="ConsumableReplaceabilityType" type="xs:string" />
  <xs:element name="ConsumableSelectibilityNumber" type="xs:string" />
  <xs:element name="ConsumableStation" type="xs:unsignedByte" />
  <xs:element name="ConsumableTypeEnum" type="xs:string" />
  <xs:element name="RegionalCartridge">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="RegionIdentifier" type="xs:unsignedByte" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ConsumableIcon">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Shape" type="xs:string" />
        <xs:element name="Rotation" type="xs:string" />
        <xs:element name="FillColor">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Red" type="xs:unsignedByte" />
              <xs:element name="Green" type="xs:unsignedByte" />
              <xs:element name="Blue" type="xs:unsignedByte" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="OutlineColor">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Red" type="xs:unsignedByte" />
              <xs:element name="Green" type="xs:unsignedByte" />
              <xs:element name="Blue" type="xs:unsignedByte" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="BackGroundColor">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Red" type="xs:unsignedByte" />
              <xs:element name="Green" type="xs:unsignedByte" />
              <xs:element name="Blue" type="xs:unsignedByte" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema><?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.hp.com/schemas/imaging/con/dictionaries/2008/10/10" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.hp.com/schemas/imaging/con/dictionaries/2008/10/10" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ConsumableID" type="xs:string" />
</xs:schema>

=== bradmAFINIA/InkCostCalculator/InkCostCalculatorL501Enhanced (1)/ConsumableConfigDyn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--          THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN.           -->
<ccdyn:ConsumableConfigDyn xsi:schemaLocation="http://www.hp.com/schemas/imaging/con/ledm/consumableconfigdyn/2007/11/19 ../schemas/ConsumableConfigDyn.xsd http://www.hp.com/schemas/imaging/con/dictionaries/1.0/ ../schemas/dd/DataDictionaryMasterLEDM.xsd" xmlns:dd="http://www.hp.com/schemas/imaging/con/dictionaries/1.0/" xmlns:dd2="http://www.hp.com/schemas/imaging/con/dictionaries/2008/10/10" xmlns:ccdyn="http://www.hp.com/schemas/imaging/con/ledm/consumableconfigdyn/2007/11/19" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<dd:Version>
		<dd:Revision>SVN-IPG-LEDM.290</dd:Revision>
		<dd:Date>2010-06-02</dd:Date>
	</dd:Version>
	<ccdyn:ProductConsumableInfo>
		<dd:NumOfUserReplaceableConsumables>2</dd:NumOfUserReplaceableConsumables>
		<dd:NumOfNonUserReplaceableConsumables>0</dd:NumOfNonUserReplaceableConsumables>
		<dd:AlignmentMode>manual</dd:AlignmentMode>
		<ccdyn:CartridgeChipInfo>disabled</ccdyn:CartridgeChipInfo>
		<dd:ConsumableSlotDirection>leftToRight</dd:ConsumableSlotDirection>
		<dd:IK>712</dd:IK>
		<ccdyn:SingleCartridgeMode>enabled</ccdyn:SingleCartridgeMode>
		<dd:StoreUsageData>disabled</dd:StoreUsageData>
		<dd:AntiTheftMode>disabled</dd:AntiTheftMode>
		<ccdyn:RewardsRegistrationStatus>
			<dd:OptedIn>false</dd:OptedIn>
			<dd:AutoSendData>false</dd:AutoSendData>
			<dd:PromptAutoSendData>false</dd:PromptAutoSendData>
		</ccdyn:RewardsRegistrationStatus>
	</ccdyn:ProductConsumableInfo>
	<ccdyn:ConsumableInfo>
		<dd:Capacity>
			<dd:MaxCapacity>0</dd:MaxCapacity>
			<dd:Unit>tenthsOfMilliliters</dd:Unit>
		</dd:Capacity>
		<ccdyn:ConsumableSubBrand>generic</ccdyn:ConsumableSubBrand>
		<ccdyn:ConsumableSegmentClass>class3</ccdyn:ConsumableSegmentClass>
		<dd:ConsumableAcceptibilityUpgradability>notSupported</dd:ConsumableAcceptibilityUpgradability>
		<dd:ConsumableContentType>markingAgent</dd:ConsumableContentType>
		<dd:ConsumableFamilyName>TIJ2</dd:ConsumableFamilyName>
		<dd2:ConsumableID>0000000000000000000000000000000000000000000000000000000000000000C02A5C00000001DC50368CA4C73A913701A6060000007C1B9F070238004C3CC7</dd2:ConsumableID>
		<dd:ConsumableKeyingDescriptor>large3</dd:ConsumableKeyingDescriptor>
		<dd:ConsumableLabelCode>CMY</dd:ConsumableLabelCode>
		<dd:ConsumableLifeState>
			<dd:ConsumableState>newGenuineHP</dd:ConsumableState>
			<dd:MeasuredQuantityState>ok</dd:MeasuredQuantityState>
			<dd:Brand>HP</dd:Brand>
			<dd:IsRefilled>false</dd:IsRefilled>
			<dd:IsSETUP>false</dd:IsSETUP>
			<dd:IsTrial>false</dd:IsTrial>
		</dd:ConsumableLifeState>
		<dd:ConsumableStateAvailableActions>
			<dd:ConsumableState>newGenuineHP</dd:ConsumableState>
			<dd:SupportedActions>
				<dd:ConsumableStateAction>acknowledge</dd:ConsumableStateAction>
				<dd:ConsumableStateAction>none</dd:ConsumableStateAction>
			</dd:SupportedActions>
			<dd:DefaultAction>acknowledge</dd:DefaultAction>
		</dd:ConsumableStateAvailableActions>
		<dd:ConsumableLevelMessagingStyle>Eureka</dd:ConsumableLevelMessagingStyle>
		<ccdyn:ConsumableLowUseAlgorithm>everyday3</ccdyn:ConsumableLowUseAlgorithm>
		<dd:ConsumablePercentageLevelRemaining>90</dd:ConsumablePercentageLevelRemaining>
		<dd:ConsumableReplaceabilityType>userReplaceable</dd:ConsumableReplaceabilityType>
		<dd:ConsumableStation>0</dd:ConsumableStation>
		<dd:ConsumableTypeEnum>inkCartridge</dd:ConsumableTypeEnum>
		<dd:RegionalCartridge>
			<dd:RegionIdentifier>21</dd:RegionIdentifier>
		</dd:RegionalCartridge>
		<dd:ConsumableIcon>
			<dd:Shape>CMYTriDots</dd:Shape>
			<dd:Rotation>rotateZero</dd:Rotation>
			<dd:FillColor>
				<dd:Red>255</dd:Red>
				<dd:Green>255</dd:Green>
				<dd:Blue>255</dd:Blue>
			</dd:FillColor>
			<dd:OutlineColor>
				<dd:Red>255</dd:Red>
				<dd:Green>255</dd:Green>
				<dd:Blue>255</dd:Blue>
			</dd:OutlineColor>
			<dd:BackGroundColor>
				<dd:Red>255</dd:Red>
				<dd:Green>255</dd:Green>
				<dd:Blue>255</dd:Blue>
			</dd:BackGroundColor>
		</dd:ConsumableIcon>
		<ccdyn:ConsumableUniqueID>00000000000000ee281b46a4c73a9137</ccdyn:ConsumableUniqueID>
	</ccdyn:ConsumableInfo>
	<ccdyn:ConsumableInfo>
		<dd:Capacity>
			<dd:MaxCapacity>0</dd:MaxCapacity>
			<dd:Unit>tenthsOfMilliliters</dd:Unit>
		</dd:Capacity>
		<ccdyn:ConsumableSubBrand>generic</ccdyn:ConsumableSubBrand>
		<ccdyn:ConsumableSegmentClass>class3</ccdyn:ConsumableSegmentClass>
		<dd:ConsumableAcceptibilityUpgradability>notSupported</dd:ConsumableAcceptibilityUpgradability>
		<dd:ConsumableContentType>markingAgent</dd:ConsumableContentType>
		<dd:ConsumableFamilyName>TIJ2</dd:ConsumableFamilyName>
		<dd2:ConsumableID>00000000000000000000000000000000000000000000000000000000000000004106000E000025616939E9782D39916E000EA0019DF285000014A00000344FC9</dd2:ConsumableID>
		<dd:ConsumableKeyingDescriptor>large3</dd:ConsumableKeyingDescriptor>
		<dd:ConsumableLabelCode>K</dd:ConsumableLabelCode>
		<dd:ConsumableLifeState>
			<dd:ConsumableState>newGenuineHP</dd:ConsumableState>
			<dd:MeasuredQuantityState>ok</dd:MeasuredQuantityState>
			<dd:Brand>HP</dd:Brand>
			<dd:IsRefilled>false</dd:IsRefilled>
			<dd:IsSETUP>false</dd:IsSETUP>
			<dd:IsTrial>false</dd:IsTrial>
		</dd:ConsumableLifeState>
		<dd:ConsumableStateAvailableActions>
			<dd:ConsumableState>newGenuineHP</dd:ConsumableState>
			<dd:SupportedActions>
				<dd:ConsumableStateAction>acknowledge</dd:ConsumableStateAction>
				<dd:ConsumableStateAction>none</dd:ConsumableStateAction>
			</dd:SupportedActions>
			<dd:DefaultAction>acknowledge</dd:DefaultAction>
		</dd:ConsumableStateAvailableActions>
		<dd:ConsumableLevelMessagingStyle>Eureka</dd:ConsumableLevelMessagingStyle>
		<ccdyn:ConsumableLowUseAlgorithm>everyday3</ccdyn:ConsumableLowUseAlgorithm>
		<dd:ConsumablePercentageLevelRemaining>80</dd:ConsumablePercentageLevelRemaining>
		<dd:ConsumableReplaceabilityType>userReplaceable</dd:ConsumableReplaceabilityType>
		<dd:ConsumableStation>1</dd:ConsumableStation>
		<dd:ConsumableTypeEnum>inkCartridge</dd:ConsumableTypeEnum>
		<dd:RegionalCartridge>
			<dd:RegionIdentifier>21</dd:RegionIdentifier>
		</dd:RegionalCartridge>
		<dd:ConsumableIcon>
			<dd:Shape>Circle</dd:Shape>
			<dd:Rotation>rotateZero</dd:Rotation>
			<dd:FillColor>
				<dd:Red>0</dd:Red>
				<dd:Green>0</dd:Green>
				<dd:Blue>0</dd:Blue>
			</dd:FillColor>
			<dd:OutlineColor>
				<dd:Red>0</dd:Red>
				<dd:Green>0</dd:Green>
				<dd:Blue>0</dd:Blue>
			</dd:OutlineColor>
			<dd:BackGroundColor>
				<dd:Red>255</dd:Red>
				<dd:Green>255</dd:Green>
				<dd:Blue>255</dd:Blue>
			</dd:BackGroundColor>
		</dd:ConsumableIcon>
		<ccdyn:ConsumableUniqueID>00000000000000b0b49cf5782d39916e</ccdyn:ConsumableUniqueID>
	</ccdyn:ConsumableInfo>
</ccdyn:ConsumableConfigDyn>
